site_name: DigiDiscussions
site_description: A nice set of topics to chat about while strolling through cyberspace
nav:
    - Home: index.md
    - Hardware: hardware.md
    - Software: software.md
    - Example: example.md
    - How: how.md
    - About: about.md
theme:
  name: material
